<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <OutputType>Library</OutputType>
    <OutputPath>../Mod/Assemblies/</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <RimWorldPath>/mnt/win_c/Program Files (x86)/Steam/steamapps/common/RimWorld</RimWorldPath>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="Assembly-CSharp">
      <HintPath>$(RimWorldPath)/RimWorldWin64_Data/Managed/Assembly-CSharp.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>$(RimWorldPath)/RimWorldWin64_Data/Managed/UnityEngine.CoreModule.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="0Harmony">
      <HintPath>$(RimWorldPath)/Mods/2009463077/Current/Assemblies/0Harmony.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <PackageReference Include="Microsoft.Data.Sqlite" Version="6.0.0" />
  </ItemGroup>

  <PropertyGroup>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
  </PropertyGroup>
</Project>